--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

-- Started on 2023-07-23 10:49:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE "Gin";
--
-- TOC entry 3315 (class 1262 OID 24871)
-- Name: Gin; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE "Gin" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'English_United States.1252';


\connect "Gin"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- TOC entry 3316 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- TOC entry 823 (class 1247 OID 24873)
-- Name: pos; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.pos AS ENUM (
    'dev',
    'dsgn',
    'test',
    'mng',
    'devop'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 24884)
-- Name: employee; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee (
    id integer NOT NULL,
    name character varying,
    "position" public.pos,
    salary integer,
    experience integer,
    about character varying
);


--
-- TOC entry 209 (class 1259 OID 24883)
-- Name: employee_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3309 (class 0 OID 24884)
-- Dependencies: 210
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.employee (id, name, "position", salary, experience, about) FROM stdin;
1	John	dev	60	2	Intern, needs help
2	Ann	dsgn	70	3	Hardworking gonna get promotion
3	Mike	test	80	4	Came from new department
4	Den	mng	110	5	Experienced man, knows his job
\.


--
-- TOC entry 3317 (class 0 OID 0)
-- Dependencies: 209
-- Name: employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.employee_id_seq', 8, true);


--
-- TOC entry 3168 (class 2606 OID 24890)
-- Name: employee employee_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (id);


-- Completed on 2023-07-23 10:49:55

--
-- PostgreSQL database dump complete
--

